name: Deno CI & Coverage

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x

    - name: Cache Deno modules
      uses: actions/cache@v3
      with:
        path: ~/.cache/deno
        key: ${{ runner.os }}-deno-${{ hashFiles('**/import_map.json') }}
        restore-keys: |
          ${{ runner.os }}-deno-

    - name: Run tests with coverage
      run: deno test --coverage=coverage

    - name: Generate LCOV coverage report
      run: deno coverage coverage --lcov > coverage.lcov

    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.lcov

    - name: Generate coverage badge
      uses: Luke-Pug/coverage-badge-action@v2
      with:
        coverageFile: coverage.lcov
        outputPath: coverage-badge.svg

    - name: Upload coverage badge artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-badge
        path: coverage-badge.svg

    - name: Commit updated badge to main
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
        commit_message: "chore: update coverage badge"
        file_pattern: coverage-badge.svg