name: Python CI

on:
  push:
    branches: [ main ]
    paths:
      - "scripts/**"
      - "tests/**"
      - "requirements.txt"
      - ".github/workflows/main.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "scripts/**"
      - "tests/**"
      - "requirements.txt"
      - ".github/workflows/main.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run linting with flake8
        run: |
          python -m flake8 scripts/ tests/
      
      - name: Run tests with pytest
        run: |
          python -m pytest tests/ -v --cov=scripts --cov-report=term-missing